apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-and-exec
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: release-debuggers-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-and-exec
subjects:
- kind: Group
  name: release-debuggers
  apiGroup: rbac.authorization.k8s.io
---