name: Terraform AWS Apply

on:
  push:
    branches:
      - mainx  # Change this to your main branch name if different
  repository_dispatch:
    types: [trigger-tf-apply]
  workflow_dispatch:

env:
  TF_VAR_key_name: keypairNov2024
  TF_VAR_workstation_ip: "0.0.0.0/0"
  TF_VAR_availability_zones: '["us-east-1a", "us-east-1b"]'
  TF_VAR_instance_type: "t2.micro"
  TF_VAR_region: "us-east-1"

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: AWS 
      shell: bash
      run: |
        pwd
        ls -la
        aws s3 ls
        env
        . ./cleanup.sh

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      env:
        TF_VAR_instance_keypair1: ${{ secrets.KEYPAIR2025 }}

    - name: Terraform Apply
      run: terraform apply --auto-approve tfplan
      env:
        TF_VAR_instance_keypair1: ${{ secrets.KEYPAIR2025 }}

    - name: Archive Terraform Plan
      if: always()
      uses: actions/upload-artifact@v5
      with:
        name: tfplan
        path: terraform/tfplan
