name: Terraform AWS Destroy

on:
  repository_dispatch:
    types: [trigger-tf-destroy]
  workflow_dispatch:

env:
  TF_VAR_key_name: keypairNov2024
  TF_VAR_workstation_ip: "0.0.0.0/0"
  TF_VAR_availability_zones: '["us-east-1a", "us-east-1b"]'
  TF_VAR_instance_type: "t2.micro"
  TF_VAR_region: "us-east-1"

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: AWS 
      shell: bash
      run: |
        pwd
        aws s3 ls
        env
        #. ./cleanup.sh
        #echo $EC2_KEYPAIR2025 > key.pem
        printf '%s\n' "$KEYPAIR2025" | base64 -d > key.pem
        ls -la
      env:
        EC2_KEYPAIR2025: ${{ secrets.KEYPAIR2025 }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Destroy
      run: terraform destroy --auto-approve

    - name: Archive Terraform Plan
      if: always()
      uses: actions/upload-artifact@v5
      with:
        name: tfplan
        path: terraform/tfplan
